
spring.application.name=security
server.port = 8081

server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://localhost:3306/security
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secretKey = djakljfkldjjeiorei2323j2klj3l2jklj3l2kj3kljilajoifjoadrioejw546u983483lakkl

